{
 "title": "Flat_predictions_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu usage gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "memory usage gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "successful responses",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(successful_requests_total[10m]) / rate(total_requests_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "flat_app_predictions_bucket", "legendFormat": "__auto" }
   ]
  }
 ]
}