services:
  flat_price_api:
    env_file:
      - ./.env
    build:
      context: ..
      dockerfile: services/Dockerfile_ml_service
    ports:
      - '${VM_PORT}:${APP_PORT}'
    volumes:
      - type: bind
        source: ../models
        target: /flat_price_api/models
      - type: bind
        source: ../logs
        target: /app/logs
    hostname: flat_predict_app

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '${VM_PROM_PORT}:${APP_PROM_PORT}'
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    hostname: prometheus

  grafana:
    image: grafana/grafana
    env_file:
      - ./.env
    ports:
      - '${VM_GRAF_PORT}:${APP_GRAF_PORT}'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
